name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v

    - name: Unit test
      run: go test
      env:
        CI: true

    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0

    - name: Run golangci-lint with reviewdog
      uses: reviewdog/action-golangci-lint@v1.1.3

    - name: golangci-lint
      uses: actions-contrib/golangci-lint@v1
      with:
        golangci_lint_version: latest-alpine
